### ISSUE TITLE
Keroku install not working

### ISSUE THREAD

**Issue by jagehring** [TwilioDevEd/call-tracking-django#7]
Getting this error when using the deploy to Heroku button.

-----> Python app detected
 !     The latest version of Python 3 is python-3.6.2 (you are using python-3.4.3, which is unsupported).
 !     We recommend upgrading by specifying the latest version (python-3.6.2).
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.4.3
 !     Requested runtime (python-3.4.3) is not available for this stack (heroku-16).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by atbaker** [comment]
Thanks for the bug @jagehring. I just updated the `runtime.txt` version - can you try it now?

**Comment by atbaker** [comment]
(going to close this ticket - happy to reopen if it's still giving you trouble)

**Comment by jagehring** [comment]
@atbaker Here is the new error

-----> Python app detected
-----> Installing python-3.6.2
-----> Installing pip
-----> Installing requirements with pip
       Collecting Django==1.8 (from -r /tmp/build_7aaf2fe3a538e93211d2215435edf738/TwilioDevEd-call-tracking-django-deba9ef/requirements.txt (line 4))
         Downloading Django-1.8-py2.py3-none-any.whl (6.2MB)
       Collecting django-bootstrap3==6.1.0 (from -r /tmp/build_7aaf2fe3a538e93211d2215435edf738/TwilioDevEd-call-tracking-django-deba9ef/requirements.txt (line 7))
         Downloading django-bootstrap3-6.1.0.tar.gz
       Collecting django-forms-bootstrap==3.0.1 (from -r /tmp/build_7aaf2fe3a538e93211d2215435edf738/TwilioDevEd-call-tracking-django-deba9ef/requirements.txt (line 8))
         Downloading django-forms-bootstrap-3.0.1.tar.gz
       Collecting django-phonenumber-field==0.7.2 (from -r /tmp/build_7aaf2fe3a538e93211d2215435edf738/TwilioDevEd-call-tracking-django-deba9ef/requirements.txt (line 9))
         Downloading django-phonenumber-field-0.7.2.tar.gz
       Collecting phonenumbers==7.0.8 (from -r /tmp/build_7aaf2fe3a538e93211d2215435edf738/TwilioDevEd-call-tracking-django-deba9ef/requirements.txt (line 10))
         Downloading phonenumbers-7.0.8.tar.gz (2.1MB)
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-gbu5ivfl/phonenumbers/setup.py", line 33, in <module>
               from phonenumbers import __version__
             File "/tmp/pip-build-gbu5ivfl/phonenumbers/phonenumbers/__init__.py", line 132, in <module>
               from .phonenumbermatcher import PhoneNumberMatch, PhoneNumberMatcher, Leniency
             File "/tmp/pip-build-gbu5ivfl/phonenumbers/phonenumbers/phonenumbermatcher.py", line 161, in <module>
               re.compile(u("(?u)(?:\\p{Z}-|-\\s)\\s*(.+)")),
             File "/app/.heroku/python/lib/python3.6/re.py", line 233, in compile
               return _compile(pattern, flags)
             File "/app/.heroku/python/lib/python3.6/re.py", line 301, in _compile
               p = sre_compile.compile(pattern, flags)
             File "/app/.heroku/python/lib/python3.6/sre_compile.py", line 562, in compile
               p = sre_parse.parse(p, flags)
             File "/app/.heroku/python/lib/python3.6/sre_parse.py", line 855, in parse
               p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
             File "/app/.heroku/python/lib/python3.6/sre_parse.py", line 416, in _parse_sub
               not nested and not items))
             File "/app/.heroku/python/lib/python3.6/sre_parse.py", line 765, in _parse
               p = _parse_sub(source, state, sub_verbose, nested + 1)
             File "/app/.heroku/python/lib/python3.6/sre_parse.py", line 416, in _parse_sub
               not nested and not items))
             File "/app/.heroku/python/lib/python3.6/sre_parse.py", line 502, in _parse
               code = _escape(source, this, state)
             File "/app/.heroku/python/lib/python3.6/sre_parse.py", line 401, in _escape
               raise source.error("bad escape %s" % escape, len(escape))
           sre_constants.error: bad escape \p at position 7
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gbu5ivfl/phonenumbers/
 !     Push rejected, failed to compile Python app.
 !     Push failed
